### ISSUE TITLE
User Module  

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#1]
# User Module 
## Description
Development of Backend Functionalities for User Management.

## Task 
- [x] [User Module  | Register Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/5)
- [x] [User Module  | Login Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/6)
- [x] [User Module  | Update Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/7)
- [x] [User Module  | Logout Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/9)
- [ ] [User Module  | Delete Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/8)
- [x] [User Module  | List Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/10)

**Attributes**
- [x]  Name
-  [x]  Phone number 
-  [x]  Password
-  [x]  Id

**Validation**
-  [x]  validateUser
-  [x]  validateEmail
-  [x]  validatePassword
-  [x]  validateName 

**Validation Test**
-  [x]  testValidateUser
-  [x]  testValidateEmail
-  [x]  testValidatePassword
-  [x]  testValidateName

**Dao**
-  [x]  insertUser 
-  [x]  updateUserPassword
-  [x]  removeUser
-  [x]  findUserById
-  [x]  findUserByNumber
-  [x]  getAllUser

**Service**
-  [x]   registerUser
-  [x]  loginUser
-  [x] getUserById 
-  [x] getAllUsers

**Service Test**
- [x] createUserTestFail
- [x] createUserTestSuccess
- [x] loginTestSuccess
- [x] loginTestFail
- [x] getUserByIdTestSuccess
- [x] getUserByIdTestFail
- [x] getAllUsersTestSuccess

**Comment by razak2004** [comment]
milestone 1 Completed
