### ISSUE TITLE
User Module | List User Feature

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#10]
# User List Feature 
## User Story
**User Story:**
As a admin i have to see how many users are using my application so this feature helps me to get the list of users

## Task 
- [ ] Implementation of DAO Layer
- [ ] Implementation of a Service Layer 
- [ ] Create JUnit TestCases 
- [ ] Ensure Test Cases are passing 
- [ ] Write comments for the methods used 

## DAO

- [ ] getAllUser

## Service 
- [ ] getUsers

## Validation 
- [ ]  admin Validation 

### Dao
- [ ] getAllUserTest
### Service
- [ ] getUsersTest
### Validation 
- [ ] admin Validation Test 
## FlowChart
```mermaid
graph TD;
  A[ Start ];
  B[ adminId Validation]
  C[ Login Validation]
  D[ InValid Entry Exception]
  E[getUsers ] 
  F[ List of Users ]
 A --> B
 B -->|Success|C
 B -->|Fail|D
 D -->H
 C --> |success| E
 C -->|Fail| I[Validation Exception]
 E -->|success|F
 E -->|Fail|G[Service Exception]
 G --> H
 F --> H[End]
