### ISSUE TITLE
Workshop Module  | Register feature  

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#11]
# Workshop Registration Process
## User Story
As a new Workshop Owner , I want a seamless registration process that allows me to sign up using my mobile number and password  ensuring a quick and hassle-free onboarding experience. This way, I can swiftly access the platform's features and start exploring without any delays.

## Task 
- [x] Implementation of DAO Layer
- [x] Validation of inputs 
- [x] Implementation of a Service Layer 
- [x] Create JUnit TestCases 
- [x] Ensure Test Cases are passing 
- [x] Write comments for the methods used 

## DAO
- [x] insertWorkShop
- [x] FindWorkShopByNumber

## Service 
- [x] registerWorkShop 

## Validation 
- [x] WorkShopCredential Validation 
- [x] WorkShop already present Validation / isValidWorkshop

### Dao
- [x] insertWorkShopTest 
- [x] FindWorkShopByNumberTest
### Service
- [x] registerWorkShop  Test
### Validation 
- [x] WorkShopInput Validations 
- [x] WorkShopCredentials Validation
- [x] isValidWorkshop

## FlowChart
```mermaid
graph TD;
  A[Start] --> B[WorkshopCredentials Validations];
  B --> |Valid|C[Active Workshop Validation];
  B --> |InValid|E[ InValidEntryException]
  E --> |Fail| H[ Registration Failed ]
  C -->| Active Workshop | D[ Register Workshop ];
  D -->|Success| J[ Registration Successfull ] 
   C -->|  Workshop not Active  | F[ Validation Exception 	 ];
   F --> | Fails | H
   J --> K[ end ]
   H -->K
