### ISSUE TITLE
WorkShop Module | Login Feature

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#12]
# Workshop Login Process
## User Story
**User Story:**
 As a registered Workshop , I want to securely log into the application with my credentials to access my personalized content and features.

## Task 
- [x] Implementation of DAO Layer
- [x] Validation of inputs 
- [x] Implementation of a Service Layer 
- [x] Create JUnit TestCases 
- [x] Ensure Test Cases are passing 
- [x] Write comments for the methods used 

## DAO

- [x] FindWorkshopByNumber

## Service 
- [x] Login Workshop 

## Validation 
- [x] workShop Number , password  Validation 
- [x] Active workShop Validation

### Dao
- [x] findWorkshopByNumber Test
### Service
- [x] LoginWorkshop  Test
### Validation 
- [x] Workshop number Password Validation Test 
- [x] Active Workshop Validation Test 
## FlowChart
```mermaid
graph TD;
  A[ Start ];
  B[ Workshop number,Password Validation]
  C[ Active Workshop Validation]
  D[ InValid Entry Exception]
  E[ Workshop PassWord Validation] 
  F[Get Workshop ID]
 A --> B
 B -->|Success|C
 B -->|Fail|D
 D -->H
 C --> |success| E
 C -->|Fail| I[Service Exception]
 E -->|success|F
 E -->|Fail|G[Service Exception]
 G --> H
 F -->|Stores in  session Storage| H[End]
