### ISSUE TITLE
WorkShop Module | Update Password Feature

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#13]
# Update WorkShop password Process
## User Story
**User Story:**
 As a WorkShop  owner i have to update my password when i forget my password 

## Task 
- [x] Implementation of DAO Layer
- [x] Validation of inputs 
- [x] Implementation of a Service Layer 
- [x] Create JUnit TestCases 
- [x] Ensure Test Cases are passing 
- [x] Write comments for the methods used 

## DAO

- [x] updateWorkShopPassword
- [x] getWorkShopsById

## Service 
- [x] updateWorkShopPassword

## Validation 
- [x]  password  Validation 
- [x] WorkShopIdValidation

### Dao
- [x] getWorkShopByIdTest
### Service
- [x] updateWorkShopPasswordTest
### Validation 
- [x]  Password Validation Test 
- [x] WorkShopId Validation Test 
## FlowChart
```mermaid
graph TD;
  A[ Start ];
  B[ WorkShop ID , Password Validation]
  C[ WorkShopId Validation]
  D[ InValid Entry Exception]
  E[ Update WorkShopPassword] 
  F[ Success Message]
 A --> B
 B -->|Success|C
 B -->|Fail|D
 D -->H
 C --> |success| E
 C -->|Fail| I[Validation Exception]
 E -->|success|F
 E -->|Fail|G[Service Exception]
 G --> H
 F --> H[End]
