### ISSUE TITLE
Workshop Module | LogOut Feature

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#14]
# Workshop Logout Feature 
## User Story
**User Story:**
After using Application as a Workshop user if i dont need to use application for a while  i have to logout my account

## Task 
- [x] Implementation of DAO Layer
- [x] Validation of inputs 
- [x] Implementation of a Service Layer 
- [x] Create JUnit TestCases 
- [x] Ensure Test Cases are passing 
- [x] Write comments for the methods used 

## DAO

- [x] findWorkshopById
- [x] updateLoginStatus

## Service 
- [x] logOutWorkshop 

## Validation 
- [x]  Login Validation 
- [x] Workshop Id Validation

### Dao
- [x] findWorkshopByID Test
### Service
- [x] logOutWorkshop  Test
### Validation 
- [x]  LoginValidation Test 
- [x] WorkshopId Validation Test 
## FlowChart
```mermaid
graph TD;
  A[ Start ];
  B[ Workshop  Id Validation]
  C[ Login Validation]
  D[ InValid Entry Exception]
  E[ update logout Status] 
  F[ Success Message]
 A --> B
 B -->|Success|C
 B -->|Fail|D
 D -->H
 C --> |success| E
 C -->|Fail| I[Validation Exception]
 E -->|success|F
 E -->|Fail|G[Service Exception]
 G --> H
 F --> H[End]
