### ISSUE TITLE
WorkShop Module | Delete Feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#15]
# WorkShop Delete Feature 
## User Story
**User Story:**
After using Appliction as a Workshop Owner  if am not satisfied with the service provided i have to delete my account

## Task 
- [ ] Implementation of DAO Layer
- [ ] Validation of inputs 
- [ ] Implementation of a Service Layer 
- [ ] Create JUnit TestCases 
- [ ] Ensure Test Cases are passing 
- [ ] Write comments for the methods used 

## DAO

- [ ] findWorkshopById

## Service 
- [ ] deleteWorkshopById

## Validation 
- [ ]  Login Validation 
- [ ] WorkshopId Validation

### Dao
- [ ] findWorkshopByID Test
### Service
- [ ] deleteWorkshopById
### Validation 
- [ ]  LoginValidation Test 
- [ ] WorkshopId Validation Test 
## FlowChart
```mermaid
graph TD;
  A[ Start ];
  B[ Workshop Id Validation]
  C[ Login Validation]
  D[ InValid Entry Exception]
  E[ Update delete Status] 
  F[ Success Message]
 A --> B
 B -->|Success|C
 B -->|Fail|D
 D -->H
 C --> |success| E
 C -->|Fail| I[Validation Exception]
 E -->|success|F
 E -->|Fail|G[Service Exception]
 G --> H
 F --> H[End]
