### ISSUE TITLE
WorkShop Module | List of Workshops  feature

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#16]
# Workshop List Feature 
## User Story
**User Story:**
As a admin i have to see how many Workshops are using my application so this feature helps me to get the list of Workshops

## Task 
- [ ] Implementation of DAO Layer
- [ ] Implementation of a Service Layer 
- [ ] Create JUnit TestCases 
- [ ] Ensure Test Cases are passing 
- [ ] Write comments for the methods used 

## DAO

- [ ] getAllWorkshops

## Service 
- [ ] getWorkshops

## Validation 
- [ ]  admin Validation 

### Dao
- [ ] getAllWorkshopsTest
### Service
- [ ] getWorkshopsTest
### Validation 
- [ ] admin Validation Test 
## FlowChart
```mermaid
graph TD;
  A[ Start ];
  B[ adminId Validation]
  C[ Login Validation]
  D[ InValid Entry Exception]
  E[getWorkshops ] 
  F[ List of Workshops ]
 A --> B
 B -->|Success|C
 B -->|Fail|D
 D -->H
 C --> |success| E
 C -->|Fail| I[Validation Exception]
 E -->|success|F
 E -->|Fail|G[Service Exception]
 G --> H
 F --> H[End]
