### ISSUE TITLE
Vehicle Module | add vehicle feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#17]
# Add Vehicle process
## User Story 
As a user i have to register my vehicle when I have to get service from a workshop

## Task 
- [ ] Implementation of Dao Layer 
- [ ] Implementation of Validation Layer 
- [ ] Implementation of Service Layer 
- [ ]  Implementation of JUnit Test Cases
- [ ] Writing methods with comments 
- [ ] Ensuring the test cases are passing 

## Dao
- [ ] addVehicle 
- [ ] findVehicleByUserid 

## Validation 
- [ ] vehicle Credentials Validation 
- [ ] duplicate vehicle validation 
- [ ] user Validation

## Service 
- [ ] createVehicle 

### Dao
- [ ] add vehicle Test 
- [ ] find vehicle by Id Test
### Validation 
- [ ] Vehicle Credentials Test 
- [ ] Duplicate Vehicle Validation Test
- [ ] User Id Validation 
### Service 
- [ ] Create Vehicle Test 

## FlowChart 

```mermaid
graph TD;
  A[Start] --> B[Vehicle  Credentials Validations];
  B --> |Valid|C[ User Id  Validation];
  B --> |InValid|E[ InValidEntryException]
  E --> |Fail| H[ Registration Failed ]
  C -->| Valid | D[ Duplicate Vehicle Validation by vehicle number  ];
  D -->|Success| J[ vehicle added  Successfull ] 
   C -->|  Invalid | F[ Validation Exception 	 ];
   F --> | Fails | H
   J --> K[ end ]
   H -->K
