### ISSUE TITLE
Vehicle Module | get Vehicle Feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#18]
# Get Vehicle process
## User Story 
As a  workshop User he wants to see the vehicle details which to be serviced. 
## Task 
- [ ] Implementation of Dao Layer 
- [ ] Implementation of Validation Layer 
- [ ] Implementation of Service Layer 
- [ ]  Implementation of JUnit Test Cases
- [ ] Writing methods with comments 
- [ ] Ensuring the test cases are passing 

## Dao
 
- [ ] findVehicleByid 

## Validation 
- [ ] vehicle id Validation 

## Service 
- [ ] getVehicleById 

### Dao
- [ ] find vehicle by Id Test
### Validation 
- [ ] vehicle Id Validation
### Service 
- [ ] getVehicleByIdTest 

## FlowChart 

```mermaid
graph TD;
  A[Start] --> B[Vehicle Id Validation];
  B --> |Valid|C[ returns vehicle Object ];
  B --> |InValid|E[ Validation Exception ]
  C --> F[ end ]
  E --> F
