### ISSUE TITLE
Vehicle Module | List Vehicles Feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#19]
# View All Vehicle process
## User Story 
As a admin I  have to see all the details of the vehicles

## Task
- [x] Implementation of dao Layer 
- [x] implementation of service Layer 
- [x] Implementation of validation layer 
- [x] Implementation of JUnit Test cases 
- [x] Ensure the test cases are passing 
- [x] write code with comments 

## Dao
- [x] getAllVehicles

## Services
- [x] getVehicles 

### Dao 
- [x] getAllVehicle Test 
### Service 
 - [x] getVehicle Test 
 
## Estimation Time : 
30 mins .

## FlowChart
```mermaid
graph TD;
A[Start]
B[ End ]
C[ Dao - get all vehicles  ] 
D[Service Get All vehicles  ] 
A --> C
C --> D 
D --> B
