### ISSUE TITLE
WorkShop Module 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#2]
# Workshop Module 
## Description
Development of Backend Functionalities for WorkShop Management.

## Task 
- [x] [Workshop Module  | Register Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/11)
- [x] [Workshop Module  | Login Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/12)
- [x] [Workshop Module  | Update Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/13)
- [x] [Workshop Module  | Logout Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/14)
- [ ] [Workshop Module  | Delete Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/15)
- [x] [Workshop Module  | List Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/16)

**Attributes**
- [x]  Name
-  [x]  Phone number 
-  [x]  Password
- [x]  Id
- [x]  Type
- [x]  address

**Validations**
- [x]  validateWorkshop
- [x] validateEmail
- [x] validatePassword
- [x] validateName
- [x] validateAddress
- [x] validate type  

**Validation Test**

- [x] testvalidateWorkshop
- [x] testValidateEmail
- [x] testValidatePassword
- [x] testValidateName
- [x] testvalidateAddress

**DAO**
- [x] insertWorkShop
- [x] findWorkShopByNumber
- [x] removeWorkShopAccount
- [x] updateWorkShopPassword
- [x] getAllWorkShops
- [x] findWorkshopsByArea
- [x] getWorkShopsById
- [x] getWorkshopsByType

**Services**
- [x] WorkShopService
- [x] loginWorkShop
- [x] getAllWorkShop
- [x] getWorkShopByArea
- [x] getWorkShopById
- [x] getWorkShopByType

**Service Tests**
- [x] registerWorkShopTestFail
- [x] loginWorkshopTest
- [x] getWorkShopByAreaTest
- [x] getWorkShopByTypeTest
- [x]  getAllWorkShopTest
- [x]  getWorkShopByIdTest

**Comment by razak2004** [comment]
Completed Milestone 1
