### ISSUE TITLE
Booking Module | Create Booking Feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#20]
# Create Booking process
## User Story 
As a desired User I have to book a service from a workshop for my vehicle when it's get breakdown .
## Task
- [ ] Implementation of DAO Layer 
- [ ] implementation of Service Layer 
- [ ] Implementation of Validation layer 
- [ ] Implementation of JUnit Test cases 
- [ ] Ensure the test cases are passing 
- [ ] write code with comments 

## Dao
- [ ] insert Booking

## Services
- [ ] Create Booking 

## Validation 
- [ ] Booking credentials Validations
- [ ] Vehicle Id Validation  

### Dao 
- [ ] insert Booking Test 
### Service 
 - [ ] Create Booking Test 
### Validation 
- [ ] Booking credentials Validation Test 
- [ ] Vehicle Id Validation  

## Estimation Time 
2 Hrs 

## FlowChart
```mermaid
graph TD;
A[Start]
B[ End ]
C[ Booking Credential Validation ] 
D[Invalid Entry Exception ] 
E[ Vehicle Id Validation]
F[Create Booking ]
G[Validation Exception]
A --> C
C -->|Invalid| D 
D --> G
C -->|Valid| E
E -->|InValid| G
E -->|Valid| F
G --> I 
F -->|Fails|I[ Service Exception ]

F -->|Success|H[Booking Raised] 

H -->B
I --> B
