### ISSUE TITLE
Booking Module | Update Request Status Feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#21]
# Update Booking request Status 
## User Story 
As a desired User I am able to cancel the booking whenever I needed to .
## Task
- [ ] Implementation of DAO Layer 
- [ ] implementation of Service Layer 
- [ ] Implementation of Validation layer 
- [ ] Implementation of JUnit Test cases 
- [ ] Ensure the test cases are passing 
- [ ] write code with comments 

## Dao
- [ ] updateRequestSts

## Services
- [ ] updateRequestStatus 

## Validation 
- [ ] Booking Id Validation  

### Dao 
- [ ] updateRequestSts Test 
### Service 
 - [ ] updateRequestStatus Test 
### Validation 
- [ ] Booking Id Validation  

## Estimation time 
45 mins 

## FlowChart
```mermaid
graph TD;
A[Start]
B[ End ]
C[ Booking Id Validation ] 
D[Validation  Exception ] 
E[ Update Request Status ]
F[Updated Request ]
G[Service Exception]
A --> C
C -->|Invalid| D 
D --> G
C -->|Valid| E
E -->|Fails | G
E -->|Success| F
G --> B


F --> B
