### ISSUE TITLE
Booking Module |  Update Accept Status Feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#22]
# Update Booking Accept Status 
## User Story 
As a Workshop User I am able to accept  the booking whenever service is need . 
## Task
- [ ] Implementation of DAO Layer 
- [ ] implementation of Service Layer 
- [ ] Implementation of Validation layer 
- [ ] Implementation of JUnit Test cases 
- [ ] Ensure the test cases are passing 
- [ ] write code with comments 

## Dao
- [ ] updateAcceptSts

## Services
- [ ] updateAccept Status 

## Validation 
- [ ] Booking Id Validation  
- [ ] WorkShop Id Validation

### Dao 
- [ ] updateAcceptSts Test 
### Service 
 - [ ] updateAcceptStatus Test 
### Validation 
- [ ] Booking Id Validation  Test
- [ ] Workshop Id Validation Test 

## FlowChart
```mermaid
graph TD;
A[Start]
B[ End ]
C[ Booking & Workshop  Id  Validation ] 
D[Validation  Exception ] 
E[ Update Accept Status ]
F[Booking Accepted ]
G[Service Exception]
A --> C
C -->|Invalid| D 
D --> G
C -->|Valid| E
E -->|Fails | G
E -->|Success| F
G --> B


F --> B
