### ISSUE TITLE
Vehicle Module 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#3]
# Vehicle Module 
## Description
Development of Backend Functionalities for User's Vehicle Management.

## Task 
- [x] [Vehicle Module  | Add vehicle  Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/17)
- [x] [Vehicle Module  | get vehicle Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/18)
- [x] [Vehicle Module  | list vehicle Feature ](https://github.com/fssa-batch3/sec_a_abdulrazak.nasriudeen__corejava_project_2/issues/19)

**Attributes**
- [x] vehicleId
- [x] user_id
- [x] vehicleType
- [x] vehicleNumber
- [x] vehicleCompany
- [x] vehicleYear
- [x] vehicleModel 

**Validations**
- [x] VehicleTypeValidation
- [x] vehicleNumberValidation
- [x] vehicleYearValidation

**Validation Test**
- [x] VehicleTypeValidationTest
- [x] VehicleNumbervalidationTest
- [x] Vehicle Year validationTest 

**Dao**
- [x] insertVehicle
- [x] removeVehicle
- [x] findVehicleByUserId
- [x] findVehicleById
- [x] getAllVehicles

**Service**
- [x] createVehicle
- [x] getVehicleById
- [x] getVehicleByUserId
- [x] getAllVehicles

**Service Test**
- [x] CreateVehicleTest
- [x] getVehicleByIdTest
- [x] getVehicleByUserId
- [x] getAllVehicles

**Comment by razak2004** [comment]
completed vehicle Module
