### ISSUE TITLE
User Module |  Register feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#5]
# User Registration Process
## User Story
As a new user, I want a seamless registration process that allows me to sign up using my mobile number and password  ensuring a quick and hassle-free onboarding experience. This way, I can swiftly access the platform's features and start exploring without any delays.

## Task 
- [x] Implementation of DAO Layer
- [x] Validation of inputs 
- [x] Implementation of a Service Layer 
- [x] Create JUnit TestCases 
- [x] Ensure Test Cases are passing 
- [x] Write comments for the methods used 

## DAO
- [x] Insert User 
- [x] FindUserByNumber

## Service 
- [x] registerUser 

## Validation 
- [x] UserCredential Validation 
- [x] User already present Validation

### Dao
- [x] insertUserTest 
- [x] findUserByIdTest
### Service
- [x] Create User Test
### Validation 
- [x] User Input Validations 
- [x] User Credentials Validation
- [x] isValidUser

## Estimation Time 
1 hour 

## FlowChart
```mermaid
graph TD;
  A[Start] --> B[User Credentials Validations];
  B --> |Valid|C[Active User  Validation];
  B --> |InValid|E[ InValidEntryException]
  E --> |Fail| H[ Registration Failed ]
  C -->| User not Active | D[ Register User ];
  D -->|Success| J[ Registration Successfull ] 
   C -->|  Active User | F[ Validation Exception 	 ];
   F --> | Fails | H
   J --> K[ end ]
   H -->A
