### ISSUE TITLE
User Module | Login feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#6]
# User Login Process
## User Story
**User Story:**
 As a registered user, I want to securely log into the application with my credentials to access my personalized content and features.

**Acceptance Criteria:**

1.  Successful login redirects me to my account's dashboard.
2.  Incorrect credentials display an error message and keep me on the login page.
3.  Clicking "Forgot Password" directs me to the password recovery page.

## Task 
- [x] Implementation of DAO Layer
- [x] Validation of inputs 
- [x] Implementation of a Service Layer 
- [x] Create JUnit TestCases 
- [x] Ensure Test Cases are passing 
- [x] Write comments for the methods used 

## DAO

- [x] FindUserByNumber

## Service 
- [x] Login User

## Validation 
- [x] User Number , password  Validation 
- [x] Active User Validation

### Dao
- [x] findUserByNumber Test
### Service
- [x] LoginUser Test
### Validation 
- [x] User number Password Validation Test 
- [x] Active User Validation Test 
## FlowChart
```mermaid
graph TD;
  A[ Start ];
  B[ User number,Password Validation]
  C[ Active User Validation]
  D[ InValid Entry Exception]
  E[ User PassWord Validation] 
  F[Get User ID]
 A --> B
 B -->|Success|C
 B -->|Fail|D
 D -->H
 C --> |success| E
 C -->|Fail| I[Service Exception]
 E -->|success|F
 E -->|Fail|G[Service Exception]
 G --> H
 F -->|Stores in  session Storage| H[End]
