### ISSUE TITLE
User Module | Update Feature

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#7]
# User Update password Process
## User Story
**User Story:**
 As a User i have to update my password when i 

## Task 
- [x] Implementation of DAO Layer
- [x] Validation of inputs 
- [x] Implementation of a Service Layer 
- [x] Create JUnit TestCases 
- [x] Ensure Test Cases are passing 
- [x] Write comments for the methods used 

## DAO

- [x] updatePassword
- [x] findUserById

## Service 
- [x] updateUserPassword

## Validation 
- [x]  password  Validation 
- [x] userId Validation

### Dao
- [x] findUserByID Test
### Service
- [x] updateUserPasswordTest
### Validation 
- [x]  Password Validation Test 
- [x] userId Validation Test 
## FlowChart
```mermaid
graph TD;
  A[ Start ];
  B[ User ID , Password Validation]
  C[ User Id Validation]
  D[ InValid Entry Exception]
  E[ Update User Password] 
  F[ Success Message]
 A --> B
 B -->|Success|C
 B -->|Fail|D
 D -->H
 C --> |success| E
 C -->|Fail| I[Validation Exception]
 E -->|success|F
 E -->|Fail|G[Service Exception]
 G --> H
 F --> H[End]
