### ISSUE TITLE
User Module | Logout feature 

### ISSUE THREAD

**Issue by razak2004** [fssa-batch3/abdulrazak.nasriudeen__corejava_project_2#9]
# User Logout Feature 
## User Story
**User Story:**
After using Appliction as a user if i dont need to use application for a while  i have to logout my account

## Task 
- [x] Implementation of DAO Layer
- [x] Validation of inputs 
- [x] Implementation of a Service Layer 
- [x] Create JUnit TestCases 
- [x] Ensure Test Cases are passing 
- [x] Write comments for the methods used 

## DAO

- [x] findUserById
- [x] updateLoginStatus.

## Service 
- [x] logOutUser

## Validation 
- [x] userId Validation
- [x] LoginValidation

### Dao
- [x] findUserByID Test
### Service
- [x] logOutUser Test
### Validation 
- [x] userId Validation Test 
- [x] loginValidationTest.
## FlowChart
```mermaid
graph TD;
  A[ Start ];
  B[ User Id Validation]
  C[ Login Validation]
  D[ InValid Entry Exception]
  E[ update logout Status] 
  F[ Success Message]
 A --> B
 B -->|Success|C
 B -->|Fail|D
 D -->H
 C --> |success| E
 C -->|Fail| I[Validation Exception]
 E -->|success|F
 E -->|Fail|G[Service Exception]
 G --> H
 F --> H[End]
